### ISSUE TITLE
[win7] "can't find .emacs.buffers" error

### ISSUE THREAD

**Issue by soterite** [ffevotte/desktop-plus#10]
I've had this problem on windows 7. The path to the file was garbled with '//', which clearly prevented .emacs.buffers from loading. This simple fix did the trick:
 
(defun desktop+--buffers-file ()
  (concat desktop-dirname ".emacs-buffers"))

Is it a bug in your original desktop+--buffers-file?

**Comment by ffevotte** [comment]
Yes, it's probably a bug. I wasn't sure that `desktop-dirname` would always end with a path separator, so I added a "/" just in case. This (unnecessary) precaution is not a problem with linux, but of course it's causing you problems on windows.

I implemented your solution in the last commit, so that the bug should now be fixed.
Please don't hesitate to test and tell me if it works.

**Comment by soterite** [comment]
Now It works like a charm.

btw... Your code keeps me more organized and saves a heck of a lot of my time each and every day. Many, many thanks indeed for your work :)

**Comment by ffevotte** [comment]
Thanks for your feedback and the time you took to diagnose the problem!

**Comment by ffevotte** [comment]
This bug fix is probably the cause for issue #14.
