### ISSUE TITLE
org mode agenda view isn't loaded

### ISSUE THREAD

**Issue by friolz** [ffevotte/desktop-plus#6]
I've created a new desktop with 4 frames. However, my agenda view dispatcher doesn't get loaded.
I suppose it should work, shouldn't it?

**Comment by ffevotte** [comment]
Very few special buffer types are supported by vanilla `desktop` (and, although I haven't checked, I suspect org agenda views aren't). And `desktop+` doesn't support them either, at least for now. Which is why it is not surprising that your org agenda dispatcher isn't saved and restored with the session.

But support for such buffers could certainly be added to `desktop+`... Could you please post a precise description of the precise type of buffers you want to save/restore, and how to create them? I don't use `org` much these days, and I'm afraid I don't know exactly what you are referring to when speaking of "agenda view dispatcher".

**Comment by friolz** [comment]
I mean hitting C-c a a as described here:
http://orgmode.org/manual/Agenda-dispatcher.html#Agenda-dispatcher

**Comment by ffevotte** [comment]
OK. I can see how to restore agenda buffers (and maybe todo lists and some of the types that `org-agenda` proposes) in a "fresh" state (i.e. how they would initially be created using
<kbd>C-a</kbd><kbd>a</kbd><kbd>something</kbd>.

However, if you also want to save & restore some state (such as the week/day view, the date displayed, etc.), it will be a lot more difficult, as it will mean looking at the internal state used by org-agenda to correctly store and restore it. If you want this kind of full integration, I would recommend requesting it a as a feature to be introduced into org itself.

If simple restoration of fresh agenda buffers is enough, I will try and implement it into `desktop+`.

**Comment by friolz** [comment]
Simple restoration would be ok. Thanks a lot for your help!

**Comment by ffevotte** [comment]
`org-agenda` buffers should now be correctly saved and restored (to a default state) in the latest version.

Only buffers created with `org-agenda-list`(<kbd>C-c</kbd><kbd>a</kbd><kbd>a</kbd>) and `org-todo-list`(<kbd>C-c</kbd><kbd>a</kbd><kbd>t</kbd>) are currently supported.

Please don't hesitate to reopen the issue if something goes wrong or you need support for another `org-agenda`-related buffer type.
